<template>
    <index-page :defaultTable="false" :show_status="false">
        <template v-slot:search-field>
            <v-select-container title="Category" field="category_id" col="3 mb-3">
                <v-select v-model="search_data.category_id" label="title" :reduce="obj => obj.id" :options="categories"
                    placeholder="--Select One--" :closeOnSelect="true" />
            </v-select-container>
            <Input v-model='search_data.from_qty' field='search_data.from_qty' type="number" title='From Qty' col="2"
                :req='false' />
            <Input v-model='search_data.to_qty' field='search_data.to_qty' type="number" title='To Qty' col="2"
                :req='false' />
            <SwitchBoolean v-model='search_data.is_zero' field='search_data.is_zero' title='Is Zero Qty Item?'
                on-label='On' off-label='Off' :req='false' col="3"></SwitchBoolean>
        </template>
        <template v-slot:table-list>
            <div class="col-md-12">
                <div class="d-flex gap-3 align-items-center justify-content-end">
                    <div class="print_action text-end">
                        <button class="p_btn" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Print"
                            v-x-tooltip @click="print('printArea', model)">
                            <i class="fas fa-print"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="my-5" id="printArea">
                <!-- <pre>{{ datas }}</pre> -->
                <!-- 🧾 Report Header (Visible in Print) -->
                <div class="text-center mb-2 report-title">
                    <h3 class="fw-bold">{{ $root.site.title }}.</h3>
                    <p class="mb-1">{{ $root.site.address }}</p>
                    <p>Email: {{ $root.site.contact_email }} | Phone: {{ $root.site.mobile1 }}</p>
                </div>

                <div class="d-flex justify-content-between align-items-center mb-3">
                    <div>
                        <h5 class="fw-bold mb-1">Available Stock</h5>
                        <small class="text-muted">Report Date: <strong>{{ reportDate }}</strong></small>
                    </div>
                    <div class="text-end">
                    </div>
                </div>

                <!-- 📊 Income Table -->
                <table class="table table-bordered align-middle">
                    <thead class="table-light">
                        <tr class="fw-bold text-center">
                            <th>#</th>
                            <th>Category</th>
                            <th>Barcode</th>
                            <th>Item Name</th>
                            <th>Total In</th>
                            <th>Total Out</th>
                            <th>Current Stock</th>
                            <th>Unit</th>
                        </tr>
                    </thead>
                    <tbody>
                        <template v-if="datas.length > 0">
                            <tr v-for="(stock, index) in datas" :key="index">
                                <td>{{ index + 1 }}</td>
                                <td class="text-md-center">{{ stock.item?.category?.title }}</td>
                                <td class="text-md-center">{{ stock.item?.barcode }}</td>
                                <td class="text-md-center">{{ stock.item?.title }}</td>
                                <td class="text-md-center">{{ stock.total_qty_in }}</td>
                                <td class="text-md-center">{{ stock.total_qty_out }}</td>
                                <td class="text-md-center">{{ stock.current_stock }}</td>
                                <td class="text-md-center">{{ stock.item?.unit?.title }}</td>
                            </tr>
                        </template>
                        <template v-else>
                            <tr>
                                <td colspan="7" class="text-md-center">
                                    <span v-if="search_data.item_id">
                                        No ledger data available. Please select an another item.
                                    </span>
                                    <span v-else>
                                        Please select an item to view its ledger report.
                                    </span>
                                </td>
                            </tr>
                        </template>
                    </tbody>
                </table>

                <!-- 📌 Footer Note -->
                <div class="mt-4 small text-muted">
                    <p>Generated by: <strong>Admin</strong></p>
                    <p>This report is system generated and does not require signature.</p>
                </div>

            </div>
        </template>
    </index-page>
</template>

<script>
import axios from "axios";
import moment from "moment";

const tableColumns = [{ field: "status", title: "Status", align: "center" }];
const json_fields = {
    Title: "Hello",
};
const model = "availableStock";

export default {
    data() {
        return {
            model: model,
            page_title: "",
            reportDate: moment().format('D MMMM, YYYY'),
            json_fields: json_fields,
            search_data: {
                category_id: null,
                is_zero: 0,
                from_qty: null,
                to_qty: null
            },
            table: {
                columns: tableColumns,
                routes: {},
                datas: [],
                meta: [],
                links: [],
            },
            datas: [], // Store the daily report data
            categories: [],  // Store account heads for the select dropdown
        };
    },

    provide() {
        return {
            validate: this.validation,
            model: this.model,
            search_data: this.search_data,
            table: this.table,
            json_fields: this.json_fields,
            search: this.search,
            resetSearchData: this.resetSearchData,
        };
    },

    methods: {
        search() {
            this.getAvailableStock();
        },
        getCategories() {
            let module = 'Item';
            axios.get(`getcategories/${module}`)
                .then((response) => {
                    this.categories = response.data;
                });
        },
        getAvailableStock() {
            axios
                .get(`report/availablestock/`, { params: this.search_data })
                .then((res) => {
                    this.datas = res.data
                })
        },
        // Capitalize the first letter of a string
        ucfirst(str) {
            if (!str) return "";
            return str.charAt(0).toUpperCase() + str.slice(1);
        },
    },

    created() {
        this.getCategories();
        this.getAvailableStock();
    },

    validators: {},
};
</script>
