<template>
    <index-page :defaultTable="false" :show_status="false">
        <template v-slot:search-field>
            <v-select-container title="Select Employee" field="search_data.employee_id" col="3">
                <v-select v-model="search_data.employee_id" label="full_name" :reduce="(obj) => obj.id"
                    :options="employees" placeholder="--Select Employee--" :closeOnSelect="true">
                </v-select>
            </v-select-container>
            <date-picker id='searchfromdate' v-model='search_data.from_date' field='search_data.from_date'
                title='From Date' placeholder='From Date' col='3' :req='false'></date-picker>
            <date-picker id='searchtodate' v-model='search_data.to_date' field='search_data.to_date' title='To Date'
                placeholder='To Date' col='3' :req='false'></date-picker>
        </template>
        <template v-slot:table-list>
            <div class="col-md-12">
                <div class="d-flex gap-3 align-items-center justify-content-end">
                    <div class="print_action text-end">
                        <button class="p_btn" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Print"
                            v-x-tooltip @click="print('printArea', model)">
                            <i class="fas fa-print"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="my-5" id="printArea">
                <!-- 🧾 Report Header (Visible in Print) -->
                <div class="text-center mb-2 report-title">
                    <h3 class="fw-bold">{{ $root.site.title }}.</h3>
                    <p class="mb-1">{{ $root.site.address }}</p>
                    <p>Email: {{ $root.site.contact_email }} | Phone: {{ $root.site.mobile1 }}</p>
                </div>
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <div>
                        <h5 class="fw-bold mb-1">Employee Ledger</h5>
                        <small class="text-muted">Name: <strong>{{ datas.employee?.full_name
                                }}</strong></small><br>
                        <small class="text-muted">Mobile: <strong>{{ datas.employee?.mobile
                        }}</strong></small><br>
                        <small class="text-muted">Address: <strong>{{ datas.employee?.address
                        }}</strong></small><br>
                        <small class="text-muted">Report Date: <strong>{{ reportDate }}</strong></small>
                    </div>
                    <div class="text-end">
                        <small class="text-muted">
                            Period:
                            <strong>{{ dateRange }}</strong>
                        </small>
                    </div>
                </div>
                <div class="row g-3">

                    <div class="col-md-12">
                        <div class="table-responsive">
                            <!-- <pre>{{ datas }}</pre> -->
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Voucher No</th>
                                        <th>Account</th>
                                        <th class="text-md-end">Debit</th>
                                        <th class="text-md-end">Credit</th>
                                        <th class="text-md-end">Balance</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr v-for="(record, index) in datas.records" :key="index">
                                        <td>{{ $filter.enFormat(record.voucher_date) }}</td>
                                        <td>{{ record.voucherno }}</td>
                                        <td> {{ record.account_name }}</td>
                                        <td class="text-md-end">{{ Number(record.dr_amount).toFixed(2) }}</td>
                                        <td class="text-md-end">{{ Number(record.cr_amount).toFixed(2) }}</td>
                                        <td class="text-md-end">{{ Number(record.running_balance).toFixed(2) }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- 📌 Footer Note -->
                <div class="mt-4 small text-muted">
                    <p>Generated by: <strong>Admin</strong></p>
                    <p>This report is system generated and does not require signature.</p>
                </div>
            </div>
        </template>
    </index-page>
</template>

<script>
import axios from "axios";
import moment from "moment";

const tableColumns = [{ field: "status", title: "Status", align: "center" }];
const json_fields = {
    Title: "Hello",
};
const model = "trialbalance";

export default {
    data() {
        return {
            model: model,
            page_title: "",
            reportDate: moment().format('D MMMM, YYYY'),
            json_fields: json_fields,
            search_data: {
                category_id: null,
                is_zero: 0,
                from_qty: null,
                to_qty: null
            },
            table: {
                columns: tableColumns,
                routes: {},
                datas: [],
                meta: [],
                links: [],
            },
            datas: [], // Store the daily report data
            employees: [],  // Store account heads for the select dropdown
        };
    },

    provide() {
        return {
            validate: this.validation,
            model: this.model,
            search_data: this.search_data,
            table: this.table,
            json_fields: this.json_fields,
            search: this.search,
            resetSearchData: this.resetSearchData,
        };
    },
    computed: {
        dateRange() {
            if (this.search_data.from_date && this.search_data.to_date) {
                return moment(this.search_data.from_date).format("D MMM, YYYY") +
                    " to " +
                    moment(this.search_data.to_date).format("D MMM, YYYY");
            }
            return "Current Month";
        }
    },
    methods: {
        search() {
            this.getEmployeeLedger();
        },
        getEmployees() {
            axios.get(
                `employees/`
            )
                .then((response) => {
                    this.employees = response.data;
                })
                .catch((error) => {
                    console.error(error);
                });
        },
        getEmployeeLedger() {
            axios
                .get(`report/employeeledger/`, { params: this.search_data })
                .then((res) => {
                    this.datas = res.data
                })
        },
        // Capitalize the first letter of a string
        ucfirst(str) {
            if (!str) return "";
            return str.charAt(0).toUpperCase() + str.slice(1);
        },
    },

    created() {
        this.getEmployeeLedger();
        this.getEmployees();
    },
    validators: {},
};
</script>
